version: '{build}'
skip_tags: true

install:
  - curl -sL -o DataEditorX/data/constants.lua https://github.com/Fluorohydride/ygopro-scripts/raw/master/constants.lua
  - curl -sL -o DataEditorX/data/strings.conf https://github.com/Fluorohydride/ygopro/raw/master/strings.conf
  - nuget restore

configuration: Release

build: 
    project: DataEditorX.sln
    parallel: true

after_build:
  - cd win32 && 7z a ../win32.zip ./* -xr!.git* -mx9 && cd ..

test: off

artifacts:
  - path: win32.zip
    name: DataEditorX-Koishi

deploy:
  release: latest
  description: 'Automatic build commit $(APPVEYOR_REPO_COMMIT) $(APPVEYOR_REPO_COMMIT_TIMESTAMP)'
  provider: GitHub
  force_update: true
  auth_token:
    secure: EQ9miMjfX/QAoBvgc6D+JLmHatLyxOEKZ/uo68QijxWW5Gp4MzB/pOH9+u2GlDVO
  on:
    branch: master
